dateModified: 1552683187
email:
  fromEmail: josef.renner@gmail.com
  fromName: 'Anna Wehrli'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  e2e0a909-7216-4ab8-87e5-aa52bf3154cb:
    name: Common
sections:
  61a820dc-d760-4060-8879-1f7686a42bca:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      5b9c62f0-83b5-4579-a3bd-afe8f211c8cf:
        enabledByDefault: true
        hasUrls: true
        uriFormat: /
        template: index
    entryTypes:
      c24d590d-e89e-4f10-ab78-9f37b7340044:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  2e061fde-6257-436c-8895-77032b31362e:
    name: 'Anna Wehrli'
sites:
  5b9c62f0-83b5-4579-a3bd-afe8f211c8cf:
    siteGroup: 2e061fde-6257-436c-8895-77032b31362e
    name: 'Anna Wehrli'
    handle: default
    language: de-CH
    hasUrls: true
    baseUrl: '@web'
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: 'Anna Wehrli'
  live: true
  schemaVersion: 3.1.25
  timeZone: Europe/Zurich
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  39b7ea48-104d-4688-8428-d1e34df3e863:
    name: Uploads
    handle: uploads
    type: craft\volumes\Local
    hasUrls: true
    url: /assets/uploads/
    settings:
      path: web/assets/uploads
    sortOrder: '1'
